site_name: OptWiki
site_description: Optimization Wiki

extra_css:
  - stylesheets/extra.css
 
plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter:
      include_source: True
      include: ["*.ipynb"]
  - social:
      cards_color:
        fill: "#7086DF" 
        text: "#FFFFFF"
  
theme:
  name: material 
  palette:
    scheme: default  
  features:
    - content.code.annotation
    - content.code.copy
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - toc.integrate
    - navigation.top
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy  


extra:    
  consent:
    title: Cookie Consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they are searching for. Your consent helps make this site better.


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true  
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: |
  &copy; 2023 Howard Heaton
  <br>
  <a href="#__consent">Cookie Settings</a>
